failure-threshold: warning
format: tty
no-color: false
no-fail: false

disable-ignore-pragma: false

strict-labels: false

trustedRegistries:
  - docker.io
  - ghcr.io
  - registry.k8s.io
  - gcr.io
  - "*.gcr.io"
  - quay.io
  - mcr.microsoft.com
  - cgr.dev

ignored:
  - DL3057
  - SC1091
  - DL3018

override:
  error:
    - DL3020
    - DL3004
    - DL4000
    - DL4004
  warning:
    - DL3006
    - DL3007
