extends: default

ignore: |
  test/crds/traefik/**

rules:
  document-start: disable
  truthy: disable
  line-length: disable
  comments: disable
  comments-indentation: disable
  new-lines:
    type: unix
  empty-lines: disable
